""" generate_skeleton.py - "The Map is the Territory (High Fidelity / Low Drag)" """
import os
import ast
import sys
import json

# [SLASH_CONFIG]: Control the resolution of the map.
MAX_DEPTH = 10
IGNORE_DIRS = {'.git', '__pycache__', 'venv', 'env', 'node_modules', '.idea', '.vscode'}
IGNORE_FILES = {'.DS_Store'}

def generate_skeleton(directory=".", output_file="project_skeleton.py"):
    """
    Scans the directory, parses .py and .json files, and generates a valid
    Python skeleton file containing only signatures, docstrings, and data schemas.
    """
    skeleton_buffer = ['""" PROJECT ARCHITECTURE SKELETON """',
                       '""" generated by SLASH_v2.1 (The Mycelial Edition) """\n',
                       'from typing import Any, Optional, List, Dict, Union, Tuple\n']

    # Header for the skeleton file

    total_files = 0

    for root, dirs, files in os.walk(directory):
        # Prune ignored directories to save IO cycles
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

        for filename in sorted(files):
            if filename in IGNORE_FILES or filename == output_file or filename == os.path.basename(__file__):
                continue

            file_path = os.path.join(root, filename)
            rel_path = os.path.relpath(file_path, directory)

            # === MODE: BONE (Python Logic) ===
            if filename.endswith(".py"):
                with open(file_path, "r", encoding="utf-8") as f:
                    try:
                        source = f.read()
                        tree = ast.parse(source)

                        skeleton_buffer.append(f"\n# {'='*40}")
                        skeleton_buffer.append(f"# MODULE: {rel_path}")
                        skeleton_buffer.append(f"# {'='*40}\n")

                        visitor = SkeletonVisitor()
                        visitor.visit(tree)
                        skeleton_buffer.append(visitor.get_output())
                        total_files += 1
                    except Exception as e:
                        skeleton_buffer.append(f"# [!] Error parsing {rel_path}: {e}\n")

            # === MODE: SPORE (Data Schema) ===
            elif filename.endswith(".json"):
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        data = json.load(f)

                    skeleton_buffer.append(f"\n# {'='*40}")
                    skeleton_buffer.append(f"# DATA_SPORE: {rel_path}")
                    skeleton_buffer.append(f"# {'='*40}\n")

                    # Convert filename to a valid variable name
                    var_name = filename.replace(".", "_").replace("-", "_")
                    schema = _skeletonize_data(data)

                    # We write it as valid python code so the LLM understands it structurally
                    skeleton_buffer.append(f"{var_name} = {json.dumps(schema, indent=4)}\n")
                    total_files += 1
                except Exception as e:
                    skeleton_buffer.append(f"# [!] Error reading spore {rel_path}: {e}\n")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(skeleton_buffer))

    print(f"🗺️  Recursive Map generated: {output_file}")
    print(f"📉  Processed {total_files} nodes.")

def _skeletonize_data(data, depth=0):
    """
    Recursively strips data down to its type skeleton.
    Prevents Context Window Bloat (High Drag).
    """
    if depth > 4: return "..."

    if isinstance(data, dict):
        return {k: _skeletonize_data(v, depth + 1) for k, v in data.items()}
    elif isinstance(data, list):
        if not data:
            return []
        # Sample the first item's structure and indicate length
        sample = _skeletonize_data(data[0], depth + 1)
        if len(data) > 1:
            return [sample, f"... ({len(data)-1} more items)"]
        return [sample]
    elif isinstance(data, str):
        return "<str>"
    elif isinstance(data, int):
        return "<int>"
    elif isinstance(data, float):
        return "<float>"
    elif isinstance(data, bool):
        return "<bool>"
    elif data is None:
        return None
    else:
        return str(type(data).__name__)

class SkeletonVisitor(ast.NodeVisitor):
    """
    Navigates the AST and extracts only the structural bones.
    """
    def __init__(self):
        self.buffer = []
        self.indent_level = 0

    def get_output(self):
        return "".join(self.buffer)

    def _indent(self):
        return "    " * self.indent_level

    def _get_args(self, node):
        if sys.version_info >= (3, 9):
            return ast.unparse(node.args)
        args = []
        for arg in node.args.args:
            a = arg.arg
            if arg.annotation: a += ": Any"
            args.append(a)
        return ", ".join(args)

    def _write_docstring(self, node):
        doc = ast.get_docstring(node)
        if doc:
            doc_lines = doc.strip().split('\n')
            if len(doc_lines) == 1:
                self.buffer.append(f'{self._indent()}""" {doc_lines[0]} """\n')
            else:
                self.buffer.append(f'{self._indent()}"""\n')
                for line in doc_lines:
                    self.buffer.append(f'{self._indent()}{line}\n')
                self.buffer.append(f'{self._indent()}"""\n')

    def visit_ClassDef(self, node):
        bases = [ast.unparse(b) for b in node.bases] if sys.version_info >= (3, 9) else [b.id for b in node.bases if isinstance(b, ast.Name)]
        bases_str = f"({', '.join(bases)})" if bases else ""
        self.buffer.append(f"\n{self._indent()}class {node.name}{bases_str}:\n")
        self.indent_level += 1
        self._write_docstring(node)
        has_children = False
        for child in node.body:
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                self.visit(child)
                has_children = True
        if not has_children: self.buffer.append(f"{self._indent()}...\n")
        self.indent_level -= 1

    def visit_FunctionDef(self, node):
        self._process_function(node)

    def visit_AsyncFunctionDef(self, node):
        self._process_function(node, is_async=True)

    def _process_function(self, node, is_async=False):
        prefix = "async " if is_async else ""
        for decorator in node.decorator_list:
            if sys.version_info >= (3, 9):
                dec_str = ast.unparse(decorator)
                self.buffer.append(f"{self._indent()}@{dec_str}\n")
            else:
                self.buffer.append(f"{self._indent()}# @decorator\n")
        args = self._get_args(node)
        ret = ""
        if node.returns:
             if sys.version_info >= (3, 9):
                 ret = f" -> {ast.unparse(node.returns)}"
             else:
                 ret = " -> Any"
        self.buffer.append(f"{self._indent()}{prefix}def {node.name}({args}){ret}:\n")
        self.indent_level += 1
        self._write_docstring(node)
        self.buffer.append(f"{self._indent()}...\n")
        self.indent_level -= 1

if __name__ == "__main__":
    generate_skeleton()